
<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Zameen Homes - Lahore Greenz - Luxury Farmhouses Project in Lahore- Only 30 Lac per Kanal</title>
    <meta name="description" content="Luxury Farmhouses Project in Lahore, Only 30 Lac per Kanal. A project of Zameen Homes.">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta property="og:title" content="Lahore Greenz Luxury Farm Houses - A Project By Zameen Homes">
    <meta property="og:image" content="https://zameenhomes.com/assets/images/blogs/649510lahoregreenzs-half-banner.jpg">
    <meta property="og:image:type" content="image/png">
    <meta property="og:image:width" content="770">
    <meta property="og:image:height" content="437">
    <link rel="shortcut icon" href="assets/images/favicon.png">
    <link rel="stylesheet" href="assets/css/animate.min.css">
    <link rel="stylesheet" href="assets/js/lib/slick/slick.css">
    <link rel="stylesheet" href="assets/js/lib/slick/slick-theme.css">
    <link rel="stylesheet" href="assets/css/style.css?1571484325">
    <link rel="stylesheet" type="text/css" href="assets/css/responsive.css">
    <link rel="stylesheet" type="text/css" href="assets/css/color.css">

    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-137394281-2"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>

<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-137394281-2');
</script>
<style>
    .ml11 {
  font-weight: 900;
  font-size: 3.5em;
  color:white;
}

.ml11 .text-wrapper {
  position: relative;
  /*display: inline-block;*/
  padding-top: 0.1em;
  padding-right: 0.05em;
  padding-bottom: 0.15em;
}
.ml11 .sup {
      vertical-align: super;
  font-size: smaller;
}

.ml11 .line {
  opacity: 0;
  position: absolute;
  left: 0;
  height: 100%;
  width: 3px;
  background-color: #fff;
  transform-origin: 0 50%;
}

.ml11 .line1 {
  top: 0;
  left: 0;
}

.ml11 .letter {
  /*display: inline-block;*/
  line-height: 1em;
}
.ml16 {
  color: #ffffff;
  padding: 12px 0;
  font-weight: 800;
  font-size: 2em;
  text-transform: uppercase;
  letter-spacing: 0.1em;
  overflow: hidden;
}

.ml16 .letter {
  display: inline-block;
  line-height: 1em;
}
.ml1 {
  font-weight: 900;
  font-size: 2em;
  color:#ffffff;
  padding-bottom:5px;
}

.ml1 .letter {
  display: inline-block;
  line-height: 1em;
}

.ml1 .text-wrapper {
  position: relative;
  display: inline-block;
  padding-top: 0.1em;
  padding-right: 0.05em;
  padding-bottom: 0.15em;
}

.ml1 .line {
  opacity: 0;
  position: absolute;
  left: 0;
  height: 3px;
  width: 100%;
  background-color: #fff;
  transform-origin: 0 0;
}

.ml1 .line1 { top: 0; }
.ml1 .line2 { bottom: 0; }
.progress {
  margin: 10px;
  width: 700px;
  height: 30px;
}
</style>

</head>

<body>
    <div class="wrapper">

        <header class="pb">

                <div class="header">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <nav class="navbar navbar-expand-lg navbar-light">
                                <a class="navbar-brand" href="./">
                                    <img src="assets/images/zameenhomesbluelogo.png" alt="Zameen Homes Logo">
                                </a>
                                <button class="menu-button" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent">
                                    <span class="icon-spar"></span>
                                    <span class="icon-spar"></span>
                                    <span class="icon-spar"></span>
                                </button>

                                <div class="navbar-collapse" id="navbarSupportedContent">
                                    <ul class="navbar-nav mr-auto">
                                        <li class="nav-item  active">
                                            <a class="nav-link" href="./">
                                                Home
                                            </a>

                                        </li>
                                        <li class="nav-item ">
                                            <a class="nav-link " href="./project" >
                                                Projects
                                            </a>

                                        </li>
                                         <li class="nav-item ">
                                            <a class="nav-link " href="./houses" >
                                                Houses
                                            </a>

                                        </li>
                                        <li class="nav-item ">
                                            <a class="nav-link " href="./vlogs" >
                                                VLogs
                                            </a>

                                        </li>
                                         <li class="nav-item ">
                                            <a class="nav-link " href="./blogs" >
                                                News Feed
                                            </a>

                                        </li>
                                        <li class="nav-item ">
                                            <a class="nav-link" href="./contact" >
                                                Contact
                                            </a>

                                        </li>
                                    </ul>
                                    <div class="d-inline my-2 my-lg-0">
                                        <ul class="navbar-nav">
                                            <li class="nav-item submit-btn">
                                                <a href="#" title="Zameen Homes 24/7 Support" class="my-2 my-sm-0 nav-link sbmt-btn">
                                                    <i class="la la-phone"></i>
                                                    <span>+92 323 4622223</span>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                    <a href="#" title="" class="close-menu"><i class="la la-close"></i></a>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>

        </header><!--header end-->

        <section class="banner hp7 hplg">

            <div class="container">

                <div class="row loadcontainer">

                  <div class="col-lg-7">

                    <h1 class="ml11">
                    <span class="text-wrapper">
                        <span class="line line1"></span>
                        <span class="letters"> 1<sup class="sup">st</sup> LUXURY FARMHOUSE <br> COMMUNITY IN PAKISTAN</span>
                     </span>
                    </h1>
                    <h1 class="ml16">Covering 100+ Acres</h1>
                    <h1 class="ml1">
                          <span class="text-wrapper">
                            <span class="line line1"></span>
                            <span class="letters">Sports Complex</span>

                           </span>
                     </h1>
                     <h1 class="ml1">
                            <span class="text-wrapper">
                            <span class="line line1"></span>
                            <span class="letters">Water Fun Park</span>
                            <span class="line line2"></span>
                            </span>
                      </h1>
                      <h1 class="ml1">
                            <span class="text-wrapper">

                            <span class="letters">Gymnasium</span>
                            <span class="line line2"></span>
                            </span>
                      </h1>
                     <h1 class="ml1">
                            <span class="text-wrapper">

                            <span class="letters">Completely Developed</span>
                            <span class="line line2"></span>
                          </span>
                    </h1>

                    </div>

                    <div class="col-lg-5">

                        <div class="widget-property-search">
                            <form id="infoform" class="row banner-search">
                               <h2 class="h2landing">Get a Call Now</h2>
                               <p class="planding" id="smsg">Enter your details & Our Consultant will reach you shortly</p>
                               <p class="planding" id="success" style="font-weight:bold;"> Thanks you for your interest. Our Representative will call you back shortly. </p>

                             <div class="form-field">
                              <label class="label">NAME *</label>
                              <input type="text" name="name" required placeholder="Your Name">
                            </div>

                             <div class="form-field">
                              <label class="label">EMAIL *</label>
                              <input type="email" name="email" required placeholder="Your Email">
                            </div>
                             <div class="form-field">
                              <label class="label" >NUMBER *</label>
                              <input type="text" name="contact" required placeholder="Phone Number">
                            </div>

                            <div class="form-field">
                              <label class="label">CITY *</label>
                              <select class="cities" name="city" required>
                                     <option value=""> Select City</option
                                     <option value="Abotabad"> Abotabad</option
                                     <option value="Attock"> Attock</option>
                                     <option value="Badin">Badin</option>
                                     <option value="Bahawalpur"> Bahawalpur</option>
                                     <option value="Bakhar">Bakhar</option>
                                     <option value="Chakwal">Chakwal</option>
                                     <option value="Chaniyot">Chaniyot</option>
                                     <option>Chechawatni</option>
                                     <option value="DGK">Dera Ghazi Khan</option>
                                     <option Value="DIK">Dera Ismael Khan</option>
                                     <option Value="Faisalabad">Faisalabad</option>
                                     <option value="Gilgit">Gilgit</option>
                                     <option value="Lahore"> Lahore</option>
                                     <option value="Sheikhupura">Sheikhupura</option>
                                     <option value="Sahiwal">Sahiwal</option>
                                     <option value="Sialkot" >Sialkot</option>
                                     <option value="Gujranwala">Gujranwala</option>
                                     <option value="Gujrat">Gujrat</option>
                                     <option value="Islamabad"> Islamabad</option>
                                     <option value="Rawalpindi"> Rawalpindi</option>
                                     <option value="Multan"> Multan</option>
                                     <option value="Naran">Naran</option>
                                     <option value="Narang"> Narang</option>
                                     <option value="Narowal"> Narowal</option>
                                     <option value="RYK"> Rahim Yar Khan</option>
                                     <option value="Karachi"> Karachi</option>
                                     <option value="Kasur">Kasur</option>
                                     <option value="Kharian">Khariyan</option>
                                     <option value="pakpatan"> Pakpatan</option>
                                     <option value="Peshawar"> Peshawar</option>
                                     <option value="Vehari"> Vehari</option>
                                     <option value="Quetta"> Quetta</option>
                                     <option value="Wah cantt">Wah Cantt</option>
                                      <option value="Hassan Abdal">Hassan abdal</option>
                                      <option value="Hyderabad"> Hyderabad</option>
                              </select>
                            </div>

                            <div class="form-field ">
                              <input type="hidden" name="title" value="Zameen  Homes Web Inquiry- Project: Lahore Greenz">


                              <input type="submit" name="send" class="btnlanding" >
                            </div>

                            </form><!--baner-form end-->
                        </div><!--widget-property-search end-->
                    </div>
                </div>
            </div>
        </section>





        <section class="categories-sec section-padding bgtextureone">
            <div class="container">

                <div class="categories-details">
                    <div class="row">
                        <div class="col-lg-1 col-md-4 col-sm-6 col-6 full">
                            <div class="categories-info">
                                <a href="./assets/resources/lahore-greenz-broucher.pdf" target="_blank" title="">
                                    <div class="catg-icon">
                                        <i class="la la-la la-file"></i>
                                    </div>
                                </a>
                                <h3><a href="./assets/resources/lahore-greenz-broucher.pdf" target="_blank" title=""> E Broucher</a></h3>
                                <a href="./assets/resources/lahore-greenz-broucher.pdf" title="" target="_blank" class="ext-link"></a>
                            </div><!--categories-info end-->
                        </div>
                        <div class="col-lg-1 col-md-4 col-sm-6 col-6 full">
                            <div class="categories-info">
                                <a href="#location" title="">
                                    <div class="catg-icon">
                                        <i class="la la-map-signs"></i>
                                    </div>
                                </a>
                                <h3><a href="#location" title="Lahore Greenz Location Map">Location Map</a></h3>

                            </div><!--categories-info end-->
                        </div>
                         <div class="col-lg-1 col-md-4 col-sm-6 col-6 full">
                            <div class="categories-info">
                                <a href="./assets/resources/Lahore-Greenz-Map.pdf" title=""  target="_blank">
                                    <div class="catg-icon">
                                        <i class="la la-map"></i>
                                    </div>
                                </a>
                                <h3> <a href="./assets/resources/Lahore-Greenz-Map.pdf"  target="_blank"> Project Master Plan</a></h3>

                            </div><!--categories-info end-->
                        </div>

                        <div class="col-lg-1 col-md-4 col-sm-6 col-6 full">
                            <div class="categories-info">
                                <a href="#payment" title="Payment Plan">
                                    <div class="catg-icon">
                                        <i class="la la-credit-card"></i>
                                    </div>
                                </a>
                                <h3><a href="#payment" title="Payment Plan by Zameen Homes">Payment Plan A & B</a> </h3> <br>




                            </div><!--categories-info end-->
                        </div>
                         <div class="col-lg-1 col-md-4 col-sm-6 col-6 full">
                            <div class="categories-info">
                                <a href="#payment" title="Payment Plan">
                                    <div class="catg-icon">
                                        <i class="la la-credit-card"></i>
                                    </div>
                                </a>
                                <h3><a href="#paymentc" title="Payment Plan by Zameen Homes">Payment Plan C</a> </h3> <br>




                            </div><!--categories-info end-->
                        </div>
                        <div class="col-lg-1 col-md-4 col-sm-6 col-6 full">
                            <div class="categories-info">
                                <a href="#why" title="">
                                    <div class="catg-icon">
                                        <i class="la la-question"></i>
                                    </div>
                                </a>
                                <h3><a href="#why" title="Why Lahore Greenz ?">Why LG</a></h3>
                                <a href="#why" title="" class="ext-link"></a>
                            </div><!--categories-info end-->
                        </div>
                         <div class="col-lg-1 col-md-4 col-sm-6 col-6 full">
                            <div class="categories-info">
                                <a href="#" title="">
                                    <div class="catg-icon">
                                        <i class="la la-tree"></i>
                                    </div>
                                </a>
                                <h3><a href="#Amenities" title="Amenities">Amenities</a></h3>
                                <a href="#Amenities" title="" class="ext-link"></a>
                            </div><!--categories-info end-->
                        </div>
                        <div class="col-lg-1 col-md-4 col-sm-6 col-6 full">
                            <div class="categories-info">
                                <a href="#" title="">
                                    <div class="catg-icon">
                                        <i class="la la-newspaper-o"></i>
                                    </div>
                                </a>
                                <h3> <a href="#"  target="_blank"> New Updates</a></h3>

                            </div><!--categories-info end-->
                        </div>
                         <div class="col-lg-1 col-md-4 col-sm-6 col-6 full">
                            <div class="categories-info">
                                <a href="#" title="">
                                    <div class="catg-icon">
                                        <i class="la la-video-camera"></i>
                                    </div>
                                </a>
                                <h3><a href="#video" title="">Video Tour</a></h3>
                                <a href="#video" title="" class="ext-link"></a>
                            </div><!--categories-info end-->
                        </div>
                         <div class="col-lg-1 col-md-4 col-sm-6 col-6 full">
                            <div class="categories-info">
                                <a href="#" title="">
                                    <div class="catg-icon">
                                        <i class="la la-line-chart"></i>
                                    </div>
                                </a>
                                <h3><a href="#video" title="">Price Analysis</a></h3>
                                <a href="#video" title="" class="ext-link"></a>
                            </div><!--categories-info end-->
                        </div>
                        <div class="col-lg-1 col-md-4 col-sm-6 col-6 full">
                            <div class="categories-info">
                                <a href="#" title="">
                                    <div class="catg-icon">
                                        <i class="la la-calculator"></i>
                                    </div>
                                </a>
                                <h3><a href="#video" title="">Return Over Investment</a></h3>
                                <a href="#video" title="" class="ext-link"></a>
                            </div><!--categories-info end-->
                        </div>
                    </div>
                </div><!--categories-details end-->
            </div>
        </section>

          <section class="popular-listing hp2 section-padding "  style="background: url('assets/images/icon/leaves.png');" id="video">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="section-heading">
                            <h3>LAHORE GREENZ COVERAGE</h3>
                        </div>
                    </div>
                </div>
                <iframe width="100%" height="600" src="https://www.youtube.com/embed/K0mwJm-9tpU" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="" style="border-style:none;background:#ffffff !important;"></iframe>

            </div>
        </section>

             <section class="certain-sec" style="background: url('https://1f72bbec9ff351e2307c-0951aea74e48cd703ee2eb5ca90acd24.ssl.cf1.rackcdn.com/goldcrest_gains_sec_bg1_2.jpg');" id="why">
            <div class="container">
                <h2>why <span>Lahore Greenz ?</span>                </h2>
                <div class="certain-sec-details-outer row">
                        <div class="certain-sec-details col-md-6 col-sm-12">
                            <div class="certain-sec-details-inner">
                                <p><b>A & B Block </b> of the project have already been sold out in a record time being the  only Premium & delivered Farmhouse Community ever. </p>
                            </div>
                        </div>
                         <div class="certain-sec-details col-md-6 col-sm-12">
                                <div class="certain-sec-details-inner" style="padding-top: 35px;">
                                <p>Ring Road phase II approach inclining to BRB just five minutes drive to Lahore Greenz will add value to the project.</p>
                            </div>
                        </div>
                        <div class="certain-sec-details col-md-6  col-sm-12">
                            <div class="certain-sec-details-inner">
                                <p>Availability of Advanced Facilities and Ametities (including water fun park & sports complex required for standard and healthy living.</p>
                            </div>
                        </div>
                        <div class="certain-sec-details col-md-6 col-sm-12">
                            <div class="certain-sec-details-inner" style="padding-top: 35px;">
                                <p> <b> Approved </b> from all Governing authorities makes it more diligence community.</p>
                            </div>
                        </div>
                        <div class="certain-sec-details col-md-6 col-sm-12">
                            <div class="certain-sec-details-inner" style="padding-top: 12px;">
                                <p>The payment Structure allows investors & end-users to gain fruitful returns as <b> Lahore Greenz </b> stands loud amongst all other Farmhouse projects</p>
                            </div>
                        </div>

                        <div class="certain-sec-details col-md-6 col-sm-12">
                            <div class="certain-sec-details-inner">
                                <p>Better Rates in comparison to other farmhouse projects in surroundings with more facilities.</p>
                            </div>
                        </div>
                    <div class="clear"></div>
                </div>
            </div>
        </section>



     <section class="popular-cities hp7 section-padding bgtextureone" id="location" >
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="section-heading">

                            <h3>Lahore Greenz Location Map</h3>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <a href="#">
                            <div class="card">
                               <!--  <div class="overlay"></div>
                                <div class="overlay-stick"></div> -->
                                <img src="assets/images/banner/lahore_greenz_location_map.jpg" alt="Lahore Greenz by Zameen Homes" class="img-fluid">
                                <div class="card-body">
                                    <h4>Lahore Greenz</h4>
                                    <i class="fa fa-angle-right"></i>
                                </div>
                            </div>
                        </a>
                    </div>

                </div>
            </div>
        </section>

        <section class="popular-cities hp7 section-padding bgtexturetwo" id="payment">
            <div class="container">
                <div class="row justify-content-center">

                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <a href="#">
                            <div class="card">
                               <!--  <div class="overlay"></div>
                                <div class="overlay-stick"></div> -->
                                <img src="assets/images/banner/web-a-and-b.jpg" alt="Block A & B Payment plan Lahore Greens - A project of Zameen Homes" class="img-fluid">
                                <div class="card-body">
                                    <h4>Payment Plan</h4>
                                    <i class="fa fa-angle-right"></i>
                                </div>
                            </div>
                        </a>
                    </div>

                </div>
            </div>
        </section>

          <section class="popular-cities hp7 section-padding bgtexturetwo" id="paymentc">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-xl-6">

                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <a href="#">
                            <div class="card">
                               <!--  <div class="overlay"></div>
                                <div class="overlay-stick"></div> -->
                                <img src="assets/images/banner/web-c-block.jpg" alt="Payment plan Lahore Greens - A project of Zameen Homes" class="img-fluid">
                                <div class="card-body">
                                    <h4>Payment Plan</h4>
                                    <i class="fa fa-angle-right"></i>
                                </div>
                            </div>
                        </a>
                    </div>

                </div>
            </div>
        </section>


           <section class="property-single-pg bgtextureone" id="Amenities" >
            <div class="container">
                <div class="property-hd-sec">

                </div><!---property-hd-sec end-->
                <div class="property-single-page-content">
                    <div class="row">
                        <div class="col-lg-8 pl-0 pr-0">
                            <div class="property-pg-left">
                                <div class="property-imgs">
                                    <div class="property-main-img">
                                        <div class="property-img">
                                            <img src="assets/images/banner/monoment.jpeg" alt="Lahore Greenz by Zameen Homes">
                                        </div><!--property-img end-->
                                        <div class="property-img">
                                            <img src="assets/images/banner/masjid.jpeg" alt="Lahore Greenz by Zameen Homes">
                                        </div><!--property-img end-->
                                        <div class="property-img">
                                            <img src="assets/images/banner/landingaa.jpeg" alt="Project of Zameen Homes">
                                        </div><!--property-img end-->
                                        <div class="property-img">
                                            <img src="assets/images/banner/gym.jpg" alt="">
                                        </div><!--property-img end-->
                                        <div class="property-img">
                                            <img src="assets/images/banner/cp.jpg" alt="">
                                        </div><!--property-img end-->
                                    </div><!--property-main-img end-->
                                    <div class="property-thumb-imgs">
                                        <div class="row thumb-carous">
                                            <div class="col-lg-4 col-md-4 col-sm-4 col-4 thumb-img">
                                                <div class="property-img">
                                                    <img src="assets/images/banner/monoment.jpeg" alt="">
                                                </div><!--property-img end-->
                                            </div>
                                            <div class="col-lg-4 col-md-4 col-sm-4 col-4 thumb-img">
                                                <div class="property-img">
                                                    <img src="assets/images/banner/masjid.jpeg" alt="Lahore Greenz by Zameen Homes Pvt Ltd">
                                                </div><!--property-img end-->
                                            </div>
                                            <div class="col-lg-4 col-md-4 col-sm-4 col-4 thumb-img">
                                                <div class="property-img">
                                                    <img src="assets/images/banner/landingaa.jpeg" alt="">
                                                </div><!--property-img end-->
                                            </div>
                                            <div class="col-lg-4 col-md-4 col-sm-4 col-4 thumb-img">
                                                <div class="property-img">
                                                    <img src="assets/images/banner/gym.jpg" alt="">
                                                </div><!--property-img end-->
                                            </div>
                                            <div class="col-lg-4 col-md-4 col-sm-4 col-4 thumb-img">
                                                <div class="property-img">
                                                    <img src="assets/images/banner/cp.jpg" alt="Zameen Homes - Hum Janain Har Jagha.">
                                                </div><!--property-img end-->
                                            </div>
                                        </div>
                                    </div><!--property-thumb-imgs end-->
                                </div><!--property-imgs end-->

                         </div><!--property-pg-left end-->
                        </div>
                        <div class="col-lg-4 pr-0">
                            <div class="sidebar layout2">
                                <div class="widget widget-form" style="margin-top: 2%;">
                                    <h2 class="widget-title"> Amenities & Features</h2>
                                    <div class="contct-info">
                                        <img src="assets/images/resources/user-img.png" alt="">
                                        <div class="contct-nf">
                                            <h3>Palm Tree Installation</h3>
                                            <h3>40 to 60 feet wide Carpeted Roads</h3>
                                            <h3>Lush Green road belts</h3>
                                             <h3>Gated Community</h3>
                                            <h3>24/7 Security Services</h3>
                                            <h3>Sports Complex</h3>
                                            <h3>State of the Art Greenery</h3>
                                            <h3>Gymnasium</h3>
                                            <h3>Monuments ObelisK</h3>
                                            <h3>Community Center</h3>
                                            <h3>Society Masjid</h3>
                                            <h3>Society Managment Office</h3>
                                            <h3>Water Fun Park</h3>



                                        </div>

                                    </div><!--contct-info end-->


                            </div><!--sidebar end-->
                        </div>
                    </div>
                </div><!--property-single-page-content end-->
            </div>
        </section>

        <!--<section class="certain-sec" style="background: url('https://1f72bbec9ff351e2307c-0951aea74e48cd703ee2eb5ca90acd24.ssl.cf1.rackcdn.com/goldcrest_gains_sec_bg1_2.jpg');" id="why">   -->
        <!--    <div class="container">-->
        <!--        <h2> Real Estate <span> Gains in the Area ?</span>  </h2>-->
        <!--        <div class="certain-sec-details-outer row"> -->


        <!--                <div class="progress">-->
        <!--                    <h2> Last 3 Years </h2>-->
        <!--                  <div id="dynamic" class="progress-bar progress-bar-success progress-bar active" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="60" style="width: 0%">-->
        <!--                    <span id="current-progress"></span>-->
        <!--                  </div>-->
        <!--                </div>-->

        <!--                 <div class="progress">-->
        <!--                     <h2> Next 3 Years</h2>-->
        <!--                  <div id="next" class="progress-bar progress-bar-success progress-bar active" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="60" style="width: 0%">-->
        <!--                    <span id="next-progress"></span>-->
        <!--                  </div>-->
        <!--                </div>-->
        <!--            <div class="clear"></div>-->
        <!--        </div>-->
        <!--    </div>-->
        <!--</section> -->






        <a href="#" title="">
            <section class="cta section-padding">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="cta-text">
                                <h2>پُر سکون، پُر آسآئش، لاھو گرینز۔  </h2>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </a>

        <section class="bottom section-padding">
            <div class="container">
                <div class="row">
                    <div class="col-xl-5 col-sm-6 col-md-4">
                        <div class="bottom-logo bottom-desc " >
                            <img src="assets/images/logozameenhomes.png" alt="Zameen Homes Logo" class="img-fluid">
                             <p style="margin-bottom:25px;">Zameen Homes showcases all the ongoing and upcoming Real Estate projects in Pakistan. We filter your requirement based on locations, Down payment and developers.
                            </p>

                        </div>
                        <img src="assets/images/icon/SECP_logo_new.png" alt="Zameen Homes at SECP">
                        <img src="assets/images/icon/fbr.jpg" alt="ZameenHomes at FBR">

                    </div>
                    <div class="col-xl-3 col-sm-6 col-md-3">
                        <div class="bottom-list">
                            <h3> Navigations </h3>
                            <ul>
                                 <li>
                                    <a href="./about" title="About Zameen Homes">About Us</a>
                                </li>
                                <li>
                                    <a href="./projects" title="Zameen Homes Projects">Latest Projects</a>
                                </li>
                                <li>
                                    <a href="#" title="">ROI Calculator</a>
                                </li>
                                <li>
                                    <a href="./vlogs" title="Zameen Homes Vlogs">Vlogs & News Feed</a>
                                </li>
                                <li>
                                    <a href="./privacy-policy" title="Privacy Policy">Privacy Policy</a>
                                </li>

                            </ul>
                        </div><!--bottom-list end-->
                    </div>
                    <div class="col-xl-4 col-sm-12 col-md-5 pl-0">
                        <div class="bottom-desc">
                            <h3>Aditional Information</h3>
                            <p> <span style="font-size: 14px;font-weight: bold;">Address: </span> 248-C Broadway Commercial DHA Phase VIII, Lahore (54000), Punjab, Pakistan.
                            </p>
                            <p> <span style="font-size: 14px;font-weight: bold;">USA : </span> 11622. Lucasville Rd Manassas Virginia (20112) USA
                            </p>
                            <p> <span style="font-size:14px;font-weight: bold;"> Contact: </span> +92 323 462 2223
                            </p>
                             <p> <span style="font-size:14px;font-weight: bold;"> USA Contact: </span> +1 703-940-5226
                            </p>

                            <p> <span style="font-size: 14px;font-weight: bold;"> Careers:  </span> <a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="f19983b18b909c94949f999e9c9482df929e9c">[email&#160;protected]</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="footer-content">
                            <div class="row justify-content-between">
                                <div class="col-xl-6 col-md-6">
                                    <div class="copyright">
                                        <p>&copy; Zameen Homes Pvt. Ltd. Powered by  <a href="https://techknot.co" title="TechKnot -Traditional to digital Knot" style="color:green" target="_blank">TechKnot  </a></b>. All Rights Resereved </p>
                                    </div>
                                </div>
                                <div class="col-xl-3 col-md-6">
                                    <div class="footer-social">

                                        <a href="https://www.facebook.com/ZameenHome/" target="_blank">
                                            <i class="fa fa-facebook"></i>
                                        </a>
                                        <a href="https://twitter.com/Zameenhomes" target="_blank">
                                            <i class="fa fa-twitter"></i>
                                        </a>
                                        <a href="https://www.instagram.com/ZameenHome/" target="_blank">
                                            <i class="fa fa-instagram" ></i>
                                        </a>
                                        <a href="https://www.youtube.com/channel/UCV-cHuYt1R3sB4xIQwa1WHw" target="_blank">
                                            <i class="fa fa-youtube"></i>
                                        </a>
                                        <a href="https://www.linkedin.com/company/zameenhomes" target="_blank">
                                            <i class="fa fa-linkedin"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- WhatsHelp.io widget -->
 <script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script type="text/javascript">
//     (function () {
//         var options = {
//             facebook: "2054560541332024", // Facebook page ID
//             whatsapp: "+923234622223", // WhatsApp number
//             call_to_action: "Chat Now", // Call to action
//             button_color: "#FF6550", // Color of button
//             position: "right", // Position may be 'right' or 'left'
//             order: "facebook,whatsapp", // Order of buttons
//         };
//         var proto = document.location.protocol, host = "whatshelp.io", url = proto + "//static." + host;
//         var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true; s.src = url + '/widget-send-button/js/init.js';
//         s.onload = function () { WhWidgetSendButton.init(host, proto, options); };
//         var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(s, x);
//     })();
 </script>
<!-- /WhatsHelp.io widget -->
<script src="//code.tidio.co/am2jzvsiba8jgyulmizwquwuz4ve7azm.js"></script>
    </div><!--wrapper end-->






    <script src="assets/js/jquery-3.3.1.min.js"></script>
    <script src="assets/js/modernizr-3.6.0.min.js"></script>
    <script src="assets/js/bootstrap.min.js"></script>
    <script src="assets/js/lib/slick/slick.js"></script>
    <script src="assets/js/scripts.js"></script>

    <!-- Maps -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>
    <script src="assets/js/map-cluster/infobox.min.js"></script>
    <script src="assets/js/map-cluster/markerclusterer.js"></script>
    <script src="assets/js/map-cluster/maps.js"></script>


 <script>
     // Wrap every letter in a span
$('.ml11 .letters').each(function(){
  $(this).html($(this).text().replace(/([^\x00-\x80]|\w)/g, "<span class='letter'>$&</span>"));
});

anime.timeline({loop: true})
  .add({
    targets: '.ml11 .line',
    scaleY: [0,1],
    opacity: [0.5,1],
    easing: "easeOutExpo",
    duration: 700
  })
  .add({
    targets: '.ml11 .line',
    translateX: [0,$(".ml11 .letters").width()],
    easing: "easeOutExpo",
    duration: 700,
    delay: 100
  }).add({
    targets: '.ml11 .letter',
    opacity: [0,1],
    easing: "easeOutExpo",
    duration: 600,
    offset: '-=775',
    delay: function(el, i) {
      return 34 * (i+1)
    }
  }).add({
    targets: '.ml11',
    opacity: 0,
    duration: 1000,
    easing: "easeOutExpo",
    delay: 4000
  });

  $('.ml16').each(function(){
  $(this).html($(this).text().replace(/([^\x00-\x80]|\w)/g, "<span class='letter'>$&</span>"));
});

anime.timeline({loop: true})
  .add({
    targets: '.ml16 .letter',
    translateY: [-100,0],
    easing: "easeOutExpo",
    duration: 1400,
    delay: function(el, i) {
      return 30 * i;
    }
  }).add({
    targets: '.ml16',
    opacity: 0,
    duration: 1000,
    easing: "easeOutExpo",
    delay: 5000
  });

  $('.ml1 .letters').each(function(){
  $(this).html($(this).text().replace(/([^\x00-\x80]|\w)/g, "<span class='letter'>$&</span>"));
});

anime.timeline({loop: true})
  .add({
    targets: '.ml1 .letter',
    scale: [0.3,1],
    opacity: [0,1],
    translateZ: 0,
    easing: "easeOutExpo",
    duration: 600,
    delay: function(el, i) {
      return 70 * (i+1)
    }
  }).add({
    targets: '.ml1 .line',
    scaleX: [0,1],
    opacity: [0.5,1],
    easing: "easeOutExpo",
    duration: 700,
    offset: '-=875',
    delay: function(el, i, l) {
      return 80 * (l - i);
    }
  }).add({
    targets: '.ml1',
    opacity: 0,
    duration: 1000,
    easing: "easeOutExpo",
    delay: 3000
  });


 </script>

    <script>
    $("#success").hide();
   var res = {

  loader: $('<div />' , { class: 'loader'}),
  container: $('.loadcontainer')

     }


      $("#success").hide();
    $('#infoform').on('submit', function (e) {
        e.preventDefault();

            var formData = $("#infoform").serialize();
            formData = formData + "&action=send";

            $.ajax({
                url: "send-email.php",
                type: "post",
                data: formData,
                beforeSend: function()
                {
                res.container.append(res.loader);
                },
                success: function (result) {
                    var ress = (result);
                    if(ress == 'success')
                    {
                        $("#smsg").hide();
                        $("#success").show();
                        res.container.find(res.loader).remove();
                        $("#infoform")[0].reset();
                    }
                }
            });

    });

   </script>

</body>


<!-- Mirrored from listing-themes.com/selio-html/07_Home_Categories_and_Advanced_Search.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 07 Feb 2019 10:04:34 GMT -->
</html>
